sst-filters: BasicTuningProvider Struct Reference
BasicTuningProvider Struct Reference
#include <TuningProvider.h>
Classes
struct CurrentTuning
struct Patch
Public Types
enum TuningMode { RETUNE_ALL = 0 }
Public Member Functions
BasicTuningProvider ()=default
Static Public Member Functions
static void note_to_omega_ignoring_tuning (float x, float &sinu, float &cosi, float sampleRate)
static float note_to_pitch_ignoring_tuning (float x)
static float note_to_pitch_inv_ignoring_tuning (float x)
static float note_to_pitch (float x)
Public Attributes
TuningMode tuningApplicationMode = RETUNE_ALL
struct sst::filters::detail::BasicTuningProvider::CurrentTuning currentTuning
std::unique_ptr< Patch > _patch = std::make_unique<Patch>()
Static Public Attributes
static constexpr double MIDI_0_FREQ = 8.17579891564371
Member Enumeration Documentation
TuningMode
enum TuningMode
Enumerator
RETUNE_ALL
Constructor & Destructor Documentation
BasicTuningProvider()
BasicTuningProvider () default
Member Function Documentation
note_to_omega_ignoring_tuning()
static void note_to_omega_ignoring_tuning (float x, float & sinu, float & cosi, float sampleRate) static
note_to_pitch_ignoring_tuning()
static float note_to_pitch_ignoring_tuning (float x) static
Referenced by BasicTuningProvider::note_to_pitch(), and BasicTuningProvider::note_to_pitch_inv_ignoring_tuning().
note_to_pitch_inv_ignoring_tuning()
static float note_to_pitch_inv_ignoring_tuning (float x) static
References BasicTuningProvider::note_to_pitch_ignoring_tuning().
note_to_pitch()
static float note_to_pitch (float x) static
References BasicTuningProvider::note_to_pitch_ignoring_tuning().
Member Data Documentation
MIDI_0_FREQ
constexpr double MIDI_0_FREQ = 8.17579891564371 static constexpr
tuningApplicationMode
TuningMode tuningApplicationMode = RETUNE_ALL
currentTuning
struct sst::filters::detail::BasicTuningProvider::CurrentTuning currentTuning
_patch
std::unique_ptr<Patch> _patch = std::make_unique<Patch>()
The documentation for this struct was generated from the following file:
TuningProvider.h